env:
  global:
  - ENCRYPTION_LABEL: 08dfceb9f496
language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"
before_install: 
  - npm install -g grunt-cli
  - gem install sass
install: npm install
before_script: grunt
after_success: "./deploy.sh"